/* =========================================================
   AFRICADÔME — catalogue des podcasts (fiches détaillées)
   Utilisé par podcast-fiche.html?id=…  — notes et avis : démonstration
   ========================================================= */

const PODCAST_REVIEWS = [
  { rating: 5, title: "Passionnant de bout en bout", author: "Aïssatou B.", when: "Semaine dernière", text: "Un sujet traité avec précision et beaucoup d'humanité. J'ai appris énormément et j'attends déjà la suite !", host: 5, content: 5, useful: 12 },
  { rating: 5, title: "Une vraie pépite", author: "Kwame O.", when: "Il y a 2 semaines", text: "Des invités pertinents, un rythme parfait pour mes trajets. Merci à l'équipe pour ce travail de fond.", host: 5, content: 5, useful: 7 },
  { rating: 4, title: "Très instructif", author: "Nadia K.", when: "Il y a 3 semaines", text: "Contenu riche et bien documenté. J'aurais aimé un ou deux exemples de plus, mais l'écoute vaut vraiment le détour.", host: 4, content: 5, useful: 4 },
  { rating: 5, title: "Je recommande", author: "Jean-Marc E.", when: "Le mois dernier", text: "L'animation est chaleureuse et le propos clair. Je l'ai partagé autour de moi.", host: 5, content: 4, useful: 3 },
];

const PODCASTS = {
  "ia-cinema": {
    title: "Comment l'IA générative transforme le cinéma nigérian", series: "Tech & IA", episode: "Épisode 18",
    host: "Koffi Mensah", guests: "Scénaristes et artistes VFX de Lagos", rating: "4,8", notes: 126, hostScore: "4,8", contentScore: "4,9",
    cover: "radio-podcast-ia.jpg", alt: "Couverture du podcast Tech & IA",
    quote: "« Nous ne demandons plus la permission de raconter nos histoires. »",
    summary: "Dans les studios de Lagos, scénaristes et artistes VFX utilisent de nouveaux outils pour réduire fortement leurs coûts.",
    more: "Storyboards générés en quelques minutes, doublage multilingue, prévisualisation des effets : l'épisode suit une équipe de production de Yaba qui intègre l'IA générative à chaque étape, tout en débattant des droits des artistes dont les œuvres nourrissent les modèles.",
    tags: ["Tech & IA", "Cinéma", "Nollywood"], date: "29/09/2026", duration: "42 min", category: "Tech & IA", reviews: [0, 2, 1],
  },
  textiles: {
    title: "Textiles africains : du tissage ancestral aux défilés de Paris", series: "Société", episode: "Épisode 09",
    host: "Awa Diop", guests: "Tisseuses de Côte d'Ivoire", rating: "4,9", notes: 98, hostScore: "4,9", contentScore: "4,8",
    cover: "radio-podcast-textiles.jpg", alt: "Créatrice de mode entourée de tissus",
    quote: "« Chaque motif raconte une famille, un village, une histoire. »",
    summary: "Rencontre avec les tisseuses de Côte d'Ivoire qui réinventent le pagne tout en préservant leurs coopératives.",
    more: "Des métiers à tisser de Korhogo aux ateliers de création parisiens, l'épisode retrace le parcours d'une étoffe et pose la question de la juste rémunération des artisanes face à la mode internationale.",
    tags: ["Société", "Mode", "Patrimoine"], date: "27/09/2026", duration: "34 min", category: "Société", reviews: [1, 0, 3],
  },
  amapiano: {
    title: "L'odyssée de l'amapiano : comment Pretoria a conquis les charts", series: "Musique", episode: "Épisode 44",
    host: "DJ Moh", guests: "Producteurs et DJ de Pretoria", rating: "4,9", notes: 211, hostScore: "5,0", contentScore: "4,8",
    cover: "radio-podcast-amapiano.jpg", alt: "Producteur devant une console de mixage",
    quote: "« Le log drum est devenu le battement de cœur d'une génération. »",
    summary: "Des townships sud-africains aux clubs londoniens, décryptage d'un phénomène planétaire.",
    more: "Né dans les fêtes de quartier de Gauteng, l'amapiano a conquis les plateformes de streaming du monde entier. DJ Moh remonte aux origines du genre et décrypte ce qui fait son succès : basses profondes, percussions jazz et culture du partage.",
    tags: ["Musique", "Amapiano", "Afrique Australe"], date: "25/09/2026", duration: "51 min", category: "Musique", reviews: [0, 1, 3],
  },
  benin: {
    title: "Les trésors du royaume du Bénin : le chemin de la restitution", series: "Histoire", episode: "Épisode 12",
    host: "Elhadj Traoré", guests: "Historiens et conservateurs", rating: "4,9", notes: 87, hostScore: "4,9", contentScore: "5,0",
    cover: "radio-podcast-benin.jpg", alt: "Sculptures en bronze dans un musée",
    quote: "« Rendre un objet, c'est aussi rendre une mémoire. »",
    summary: "L'histoire des bronzes d'Edo et le mouvement panafricain de réappropriation du patrimoine.",
    more: "Pillés en 1897, les bronzes de l'ancien royaume du Bénin sont aujourd'hui au cœur des débats sur les restitutions. L'épisode raconte leur histoire, les retours déjà obtenus et les projets de musées qui doivent les accueillir.",
    tags: ["Histoire", "Patrimoine", "Restitutions"], date: "22/09/2026", duration: "29 min", category: "Histoire", reviews: [2, 0, 1],
  },
  "creative-talks-47": {
    title: "Afrobeats & conquête mondiale : qui contrôle les catalogues ?", series: "Creative Talks", episode: "Épisode 47",
    host: "Mireille Kouadio", guests: "Adaeze Okafor & Femi Balogun", rating: "4,8", notes: 143, hostScore: "4,9", contentScore: "4,7",
    cover: "podcast-ep47.jpg", alt: "Concert d'afrobeats devant une foule",
    quote: "« Le succès mondial ne vaut rien si les droits partent ailleurs. »",
    summary: "Labels, distributeurs et plateformes : qui possède vraiment la musique africaine qui fait danser le monde ?",
    more: "Mireille Kouadio reçoit une avocate spécialisée et un producteur de Lagos pour décortiquer les contrats d'édition, les rachats de catalogues et les stratégies des artistes qui choisissent de rester indépendants.",
    tags: ["Musique", "Business", "Droits d'auteur"], date: "23/09/2026", duration: "52 min", category: "Musique", reviews: [1, 3, 2],
  },
  "creative-talks-46": {
    title: "Financer le cinéma indépendant au Nigeria et au Sénégal", series: "Creative Talks", episode: "Épisode 46",
    host: "Mireille Kouadio", guests: "Ndèye Fall & Chidi Okeke", rating: "4,7", notes: 64, hostScore: "4,8", contentScore: "4,7",
    cover: "podcast-ep46.jpg", alt: "Caméra de cinéma sur un plateau de tournage",
    quote: "« Un film indépendant se finance comme une mosaïque. »",
    summary: "Fonds publics, coproductions, préventes aux plateformes : deux producteurs partagent leurs méthodes.",
    more: "De Dakar à Lagos, comment boucler le budget d'un long-métrage sans perdre sa liberté artistique ? Les invités détaillent leurs montages financiers, leurs erreurs et leurs conseils pour les jeunes réalisateurs.",
    tags: ["Cinéma", "Financement", "Société"], date: "16/09/2026", duration: "44 min", category: "Société", reviews: [2, 1, 0],
  },
  "sahel-rhythms": {
    title: "Sahel Rhythms : musique & héritages sonores", series: "Série originale", episode: "8 épisodes",
    host: "Elhadj Traoré", guests: "Musiciens du Mali, du Niger et du Tchad", rating: "5,0", notes: 52, hostScore: "5,0", contentScore: "5,0",
    cover: "videos-top-tombouctou.jpg", alt: "Vue aérienne de Tombouctou au coucher du soleil",
    quote: "« Le Sahel chante depuis des siècles, il suffit de tendre l'oreille. »",
    summary: "Une série immersive à travers les musiques du Sahel, entre traditions et créations contemporaines.",
    more: "Épisode après épisode, Elhadj Traoré part à la rencontre de musiciens, griots et producteurs qui font vivre les musiques sahéliennes, des instruments traditionnels aux studios d'aujourd'hui.",
    tags: ["Musique", "Patrimoine", "Sahel"], date: "10/09/2026", duration: "8 × 30 min", category: "Musique", reviews: [0, 1, 2],
  },
  fintech: {
    title: "Fintech & Création : la monétisation des créateurs", series: "Série originale", episode: "6 épisodes",
    host: "Awa Diop", guests: "Fondateurs de start-up et créateurs", rating: "4,7", notes: 71, hostScore: "4,8", contentScore: "4,6",
    cover: "videos-top-mobilite-rwanda.jpg", alt: "Un entrepreneur dans un atelier d'assemblage de véhicules électriques",
    quote: "« Le mobile money a changé la façon dont les créateurs sont payés. »",
    summary: "Paiements mobiles, abonnements, financement participatif : comment les créateurs africains vivent de leur art.",
    more: "Awa Diop explore les nouveaux outils financiers qui permettent aux créateurs du continent de monétiser leur audience, et les pièges à éviter pour garder le contrôle de leurs revenus.",
    tags: ["Tech & IA", "Business", "Créateurs"], date: "05/09/2026", duration: "6 × 35 min", category: "Tech & IA", reviews: [3, 2, 1],
  },
  griots: {
    title: "Paroles de griots 2.0 : storytelling & mythes modernes", series: "Série originale", episode: "10 épisodes",
    host: "Koffi Mensah", guests: "Conteurs et auteurs", rating: "4,9", notes: 89, hostScore: "4,9", contentScore: "4,9",
    cover: "videos-indigo-bogolan.jpg", alt: "Une créatrice ajuste des tissus teints à l'indigo sur un mannequin",
    quote: "« Le griot d'aujourd'hui raconte aussi sur les réseaux. »",
    summary: "Des conteurs revisitent les grands récits africains et inventent les mythes de demain.",
    more: "Chaque épisode confie un récit fondateur à un conteur ou une autrice contemporaine, qui le réinterprète pour un public d'aujourd'hui, entre tradition orale et création sonore.",
    tags: ["Histoire", "Storytelling", "Culture"], date: "01/09/2026", duration: "10 × 25 min", category: "Histoire", reviews: [1, 0, 3],
  },
  "afro-inspiration": {
    title: "Afro Inspiration : le best-of de la semaine", series: "Afro Inspiration", episode: "Hebdomadaire",
    host: "Fatou Diallo & Kemi Adewale", guests: "Artistes de la semaine", rating: "4,8", notes: 305, hostScore: "4,9", contentScore: "4,7",
    cover: "videos-afrobeats-scene.jpg", alt: "Une chanteuse et son orchestre sur une scène dorée",
    quote: "« Le meilleur de la semaine, en une heure. »",
    summary: "Les moments forts de la matinale Afro Inspiration : sessions live, interviews et nouveautés.",
    more: "Chaque semaine, Fatou Diallo et Kemi Adewale sélectionnent les meilleurs moments de leur matinale : sessions acoustiques, découvertes et rencontres avec les artistes qui font l'actualité.",
    tags: ["Musique", "Afrobeats", "Live"], date: "30/09/2026", duration: "58 min", category: "Musique", reviews: [0, 3, 1],
  },
  "voix-terrain": {
    title: "Voix du terrain : la parole aux marchés d'Afrique", series: "Voix du terrain", episode: "Épisode 1",
    host: "La rédaction Africadôme", guests: "Commerçantes et commerçants", rating: "4,8", notes: 77, hostScore: "4,7", contentScore: "4,9",
    cover: "journaliste-micro.jpg", alt: "Une journaliste interviewe une commerçante dans un marché",
    quote: "« Le marché, c'est le premier réseau social d'Afrique. »",
    summary: "Un journalisme de terrain qui donne la voix à celles et ceux qui font l'économie réelle.",
    more: "Micro tendu, nos reporters arpentent les marchés de Dakar, Douala et Lomé pour raconter le quotidien, les combines et les rêves des commerçants qui font vivre les villes.",
    tags: ["Société", "Reportage", "Économie"], date: "20/09/2026", duration: "38 min", category: "Société", reviews: [2, 3, 0],
  },
  cosmos: {
    title: "Écouter les confins du cosmos depuis le désert du Karoo", series: "Sciences", episode: "Épisode spécial",
    host: "La rédaction Africadôme", guests: "Astrophysiciennes et ingénieurs", rating: "4,9", notes: 58, hostScore: "4,8", contentScore: "5,0",
    cover: "videos-top-karoo.jpg", alt: "Une astrophysicienne près d'un radiotélescope sous un ciel étoilé",
    quote: "« Le silence du Karoo est idéal pour écouter l'univers. »",
    summary: "Au cœur de l'Afrique du Sud, des scientifiques africains participent à l'exploration de l'univers.",
    more: "Le désert du Karoo accueille des radiotélescopes parmi les plus sensibles au monde. L'épisode donne la parole aux chercheuses et ingénieurs africains qui y travaillent et aux jeunes qu'ils inspirent.",
    tags: ["Tech & IA", "Sciences", "Afrique Australe"], date: "18/09/2026", duration: "46 min", category: "Tech & IA", reviews: [1, 2, 0],
  },
  pantsula: {
    title: "Pantsula 2.0 : la danse urbaine comme manifeste", series: "New Sounds", episode: "Épisode 7",
    host: "DJ Moh", guests: "Danseurs et chorégraphes", rating: "4,8", notes: 94, hostScore: "4,9", contentScore: "4,7",
    cover: "videos-top-pantsula.jpg", alt: "Danseurs de rue lors d'une battle dans un entrepôt",
    quote: "« Danser le pantsula, c'est prendre la parole avec le corps. »",
    summary: "Né dans les townships, le pantsula devient un langage artistique et politique pour une nouvelle génération.",
    more: "DJ Moh suit des crews de Johannesburg et de Soweto qui réinventent cette danse emblématique, entre battles, création chorégraphique et transmission aux plus jeunes.",
    tags: ["Musique", "Danse", "Culture"], date: "12/09/2026", duration: "40 min", category: "Musique", reviews: [3, 0, 2],
  },
};
